### PR TITLE
fix: h4s in docs overlay preceding text

### LINKED ISSUE #246: .content :global(h4) is overlaying previous paragraph
As mentioned in the title,  [padding-block-start: 10rem;  used in .content :global(h4) selector](https://github.com/sveltejs/sites/blob/5bf13ac400a4e01806ffd9eabd4ba047e111b51c/packages/site-kit/src/lib/components/docs/Main.svelte#L207) is overlaying partial of the previous paragraph. More details can be seen in the below screenshots.
Screen Shot 2021-12-23 at 10 18 33 PM

This is causing couple usability issues:
1. Last sentence of the previous paragraph cannot be selected with mouse. If there's a link in the last sentence, that cannot be clicked. 
2. Link of the current header shows up in the wrong location:
Screen Shot 2021-12-23 at 10 18 59 PM

Also note that currently when a link is opened, it's scrolled a bit lower from the top of the page, hence it's visible even when the top navigation bar is visible. If the `padding-block-start` is completely removed, then the opened link's title will be at the top of the page hidden behind the top navigation bar.

### PR DESCRIPTION
**Pull request by gtm-nayan**
Closes #246

Avoids #73 in a slightly different way, see https://nicolasgallagher.com/jump-links-and-viewport-positioning/demo/#method-B

### CODE REVIEW

File: packages/site-kit/src/lib/components/docs/Main.svelte [hunk 1]
```diff
@@ -200,20 +200,23 @@
...
+	.content :global(h4::before) {
+		display: block;
+		content: ' ';
+		block-size: var(--nav-h);
+		margin-block-start: calc(-1 * var(--nav-h));
 	}
 
-	.content :global(h4 > .anchor) {
-		inset-block-start: 0.05em;
+	.content :global(h4 > em) {
```
Comment (gtm-nayan) [inline packages/site-kit/src/lib/components/docs/Main.svelte:218]: Github seems to be messing up the diff here, more readable diff is
image

**Review by bluwy — APPROVED** [review]
